
// BOARD
export const REQUEST_GET_BOARD = 'REQUEST_GET_BOARD';
export const GET_BOARD = 'GET_BOARD';
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'

export const REQUEST_UPDATE_BOARD = 'REQUEST_GET_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'


// Player
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const CREATE_NEW_PLAYER = 'CREATE_NEW_PLAYER';
export const REQUEST_PLAYER_READY = 'REQUEST_PLAYER_READY';
export const PLAYER_READY = 'PLAYER_READY';
export const PLAYER_READY_SUCCESS = 'PLAYER_READY_SUCCESS';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';


// Game Play
export const REQUEST_GAME_PLAY = 'REQUEST_GAME_PLAY';
export const GAME_PLAY = 'GAME_PLAY';
export const GAME_PLAY_SUCCESS = 'GAME_PLAY_SUCCESS';

export const REQUEST_RAND_NUM = 'REQUEST_RAND_NUM';
export const RAND_NUM = 'RAND_NUM';
export const RAND_NUM_SUCCESS = 'RAND_NUM_SUCCESS';

export const REQUEST_RESET_GAME = 'REQUEST_RESET_GAME';
export const RESET_GAME = 'RESET_GAME';
export const RESET_GAME_SUCCESS = 'RESET_GAME_SUCCESS';

// Game Phase
export const CREATE_NEW_PLAYER_PHASE = 'CREATE_NEW_PLAYER_PHASE';
export const PENDING_GAME_PHASE = 'PENDING_GAME_PHASE';
export const WIN_GAME_PHASE = 'WIN_GAME_PHASE';
export const LOSE_GAME_PHASE = 'LOSE_GAME_PHASE';
export const INGAME_PHASE = 'INGAME_PHASE'; 